import { useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { ReportData, StakeholderLens } from '@/types/database';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { 
  SectionHeader, 
  DiagnosisSummary,
  WeightedParameterList,
  DevelopmentFocus,
} from '@/components/report/ui';
import { InlineMaturity } from '@/components/report/ui/MaturityBadge';
import { BookOpen, Copy, Check } from 'lucide-react';
import { toast } from 'sonner';

interface ReportContextValue {
  reportData: ReportData;
  activeLens: StakeholderLens;
  currentScore: number;
}

interface ParameterScore {
  parameterName: string;
  displayName?: string;
  score: number;
  rationale?: string;
  category?: string;
  evidence?: { quotes?: string[]; scenes?: string[] };
}

// All categories relevant to a Series Bible
const BIBLE_PARAM_MATCHERS = [
  // Core Premise
  (p: ParameterScore) =>
    p.parameterName?.includes('concept') ||
    p.parameterName?.includes('hook') ||
    p.parameterName?.includes('compressibility') ||
    p.parameterName?.includes('familiarity') ||
    p.parameterName?.includes('logline'),
  // World Rules
  (p: ParameterScore) =>
    p.parameterName?.includes('world') ||
    p.parameterName?.includes('setting') ||
    p.parameterName?.includes('plausibility') ||
    p.parameterName?.includes('spatial') ||
    p.category === 'World & Logic',
  // Tonal Guardrails
  (p: ParameterScore) =>
    p.parameterName?.includes('tone') ||
    p.parameterName?.includes('genre') ||
    p.parameterName?.includes('thematic') ||
    p.parameterName?.includes('symbol') ||
    p.parameterName?.includes('motif'),
  // Character Trajectories
  (p: ParameterScore) =>
    p.parameterName?.includes('want_vs_need') ||
    p.parameterName?.includes('transformation') ||
    p.parameterName?.includes('psychological') ||
    p.parameterName?.includes('agency') ||
    p.parameterName?.includes('flaw'),
  // Series Engine
  (p: ParameterScore) =>
    p.parameterName?.includes('serial') ||
    p.parameterName?.includes('episode') ||
    p.parameterName?.includes('franchise') ||
    p.parameterName?.includes('retention') ||
    p.parameterName?.includes('momentum') ||
    p.category === 'Web Series',
];

export default function SeriesBibleExtract() {
  const context = useOutletContext<ReportContextValue>();
  const { reportData, currentScore } = context;
  const [copied, setCopied] = useState(false);

  // Consolidate all bible-relevant parameters (deduplicated)
  const bibleParameters = useMemo(() => {
    const allParams = (reportData.parameterScores || []) as ParameterScore[];
    const seen = new Set<string>();
    const result: Array<{
      parameterName: string;
      displayName: string;
      score: number;
      rationale?: string;
      weight: number;
    }> = [];

    for (const p of allParams) {
      if (seen.has(p.parameterName)) continue;
      if (BIBLE_PARAM_MATCHERS.some(matcher => matcher(p))) {
        seen.add(p.parameterName);
        result.push({
          parameterName: p.parameterName,
          displayName: p.displayName || p.parameterName,
          score: p.score,
          rationale: p.rationale,
          weight: 1.0,
        });
      }
    }
    return result;
  }, [reportData.parameterScores]);

  // Section score
  const sectionScore = useMemo(() => {
    if (bibleParameters.length === 0) return currentScore;
    return Math.round(bibleParameters.reduce((s, p) => s + p.score, 0) / bibleParameters.length);
  }, [bibleParameters, currentScore]);

  // Copy summary logic
  const generatePlainTextSummary = () => {
    const title = reportData.scriptMetadata?.title || 'Untitled Script';
    let summary = `SERIES BIBLE EXTRACT - ${title}\n`;
    summary += `${'='.repeat(40)}\n\n`;

    bibleParameters.forEach(p => {
      summary += `${p.displayName}: ${p.score}/100\n`;
      if (p.rationale) summary += `  ${p.rationale}\n`;
      summary += '\n';
    });

    summary += `\nGenerated by Pulse V2 | ${new Date().toLocaleDateString()}`;
    return summary;
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generatePlainTextSummary());
      setCopied(true);
      toast.success('Bible summary copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy to clipboard');
    }
  };

  const basePath = window.location.pathname.split('/bible')[0];

  if (!context) {
    return <div className="text-center py-12 text-muted-foreground">Loading...</div>;
  }

  return (
    <div className="space-y-8">
      {/* Section Header */}
      <SectionHeader
        title="Series Bible Extract"
        subtitle="World rules, character trajectories, and tonal guardrails"
        icon={BookOpen}
        score={sectionScore}
      >
        <InlineMaturity score={sectionScore} />
      </SectionHeader>

      {/* Diagnosis Summary */}
      <DiagnosisSummary
        parameters={bibleParameters}
        categoryName="Series Bible"
        developmentLink={`${basePath}/development`}
      />

      {/* Weighted Parameter Breakdown */}
      <WeightedParameterList
        parameters={bibleParameters}
        title="Series Bible Parameter Breakdown"
        initiallyExpanded={false}
        defaultVisibleCount={6}
      />

      {/* Development Focus */}
      {(() => {
        const items = bibleParameters
          .filter(p => p.score < 70)
          .sort((a, b) => a.score - b.score)
          .map(p => ({ title: p.displayName, description: p.rationale || '' }));
        return items.length > 0 ? (
          <DevelopmentFocus
            sectionName="Series Bible"
            items={items}
            developmentPath={`${basePath}/development`}
            relatedSections={[
              { label: 'Story Diagnosis', path: `${basePath}/story` },
              { label: 'Character Diagnosis', path: `${basePath}/characters` },
              { label: 'Format Diagnosis', path: `${basePath}/format` },
            ]}
          />
        ) : null;
      })()}

      {/* Copy Summary Footer */}
      <Card className="p-5 bg-card border border-border">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="text-sm font-semibold">Quick Reference Export</h4>
            <p className="text-sm text-muted-foreground">
              Copy a plain-text summary for writers' rooms, pitch decks, or production docs.
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopyToClipboard}
            className="gap-2"
          >
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? 'Copied!' : 'Copy Bible Summary'}
          </Button>
        </div>
      </Card>
    </div>
  );
}
